services:
  - type: web
    name: booking-scraper
    env: python
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: python main.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
    plan: free # O el plan que est√©s usando
    runtimeVersion: "3.11" # <--- FORZAMOS PYTHON 3.11
